### ISSUE TITLE
Im getting a crash on 1.19.4 when trying to make a world

### ISSUE THREAD

**Issue by casmin7** [GalievDev/SpawnWorldSetter#1]
[latest.log](https://github.com/GalievDev/SpawnWorldSetter/files/11220780/latest.log)
[crash-2023-04-13_12.56.39-server.txt](https://github.com/GalievDev/SpawnWorldSetter/files/11220789/crash-2023-04-13_12.56.39-server.txt)

Also I dont have any other mods except this and kotlin lang
And the config has generated

**Comment by GalievDev** [comment]
Bug fixed - https://modrinth.com/mod/spawn-world-setter/version/1.0.1-1.19.4

**Comment by casmin7** [comment]
That was fast!
Tysm you are awesome
