### ISSUE TITLE
Doesn't work on 1.20.1

### ISSUE THREAD

**Issue by Martmists-GH** [GalievDev/SpawnWorldSetter#2]
The world loads in empty and never loads. The log just spams `[Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?`

**Comment by Martmists-GH** [comment]
I think it's caused by https://github.com/GalievDev/spawn-dimension-setter/blob/master/src/main/kotlin/net/galiev/sws/helper/WorldHelper.kt#L36-L53 being an infinite loop. My custom dimension is empty, but KubeJS is configured to create a spawn platform for each user after they spawn.

**Comment by GalievDev** [comment]
Hello! Can you check with new version https://modrinth.com/mod/spawn-dimension-setter/version/1.1-1.20

You should change `safeCheck` parameter to false value in  `config.json` file
